[package]
name = "ex1"
version = "0.0.1"
authors = ["George Malandrakis <malandrakisgeo@gmail.com>"]
edition = "2018"

description = "Scan a csv file, query it"

repository = ""

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }

[[bin]]
name="ex1"
path = "main.rs"
